### ISSUE TITLE
Kunden anlegen

### ISSUE THREAD

**Issue by chrisitananese** [Tomschi/uni-sese_ws15#1]
Für einen Kundendatensatz sind folgende Daten notwendig:

Name
Geburtsdatum
Geschlecht
Rechnungsadresse
Firmenname(optional)
Notiz
Rabatt
Telefonnummer
E-Mail
WEB
FAX

Die Daten werden über die Webseite durch den Mitarbeiter eingegeben.

Nachdem der Kunde angelegt wurde, wird ein entsprechender Eintrag in ein logfile geschrieben.

**Subtasks**
- [x] Kundenmenü und item "Kunde anlegen" erstellen #69
- [x] Kunde anlegen Seite fixen #70 
- [x] Kunde anlegen Pflichtfelder #90 
- [x] Kunde anlegen Validierung #91 
- [x] Kunde anlegen Runtime Exception #92 
- [x] Kunde anlegen - zukünftiger Geburtstag #93
- [x] Kunde anlegen - Strasse/Text/Zahlen #94
- [x] Kunde anlegen - negative Rabatte #95 
- [x] Kunden anlegen - Speichern nicht möglich #104
- [x] Kunde anlegen - Speichern OK/NOK Message #105

**Comment by alex3772** [comment]
nicht nach spec erledigt.

**Comment by develope80** [comment]
Alle Tasks abgeschlossen
