### ISSUE TITLE
Buchungen stornieren

### ISSUE THREAD

**Issue by chrisitananese** [Tomschi/uni-sese_ws15#17]
Bei der Detailansicht einer Buchung gibt es einen Button mit der Beschriftung “stornieren”.

Dieser Button ist nicht klickbar/ausgegraut wenn:
* die Stornierfrist abgelaufen ist
  * bis X Tage vor Startdatum der Buchung. (X ist im System definiert)
* bereits eine Rechnung angelegt wurde.

Bei Betätigung des Buttons wird die Buchung aus dem System gelöscht. Diese Löschung kann nicht mehr rückgängig gemacht werden.

Nachdem die Rechnung erstellt wurde, wird ein entsprechender Eintrag in ein logfile geschrieben.

**Subtasks**
- [x] Button zum stornieren einer Buchung #76
- [x] Buchung storniert Meldung #77
- [x] Storno - Buchung/Reservierung innhalb einer spezifizierten Zeit #87

**Comment by chrisitananese** [comment]
Hab als DEADLIN im mom 10Tage eingestllt können wir dann ändern
