### ISSUE TITLE
Build Infrastructure und Sonstiges

### ISSUE THREAD

**Issue by chrisitananese** [Tomschi/uni-sese_ws15#59]
Um eine korrekte Auslieferung zu ermöglichen muss die Build Infrastructure komplett funktionieren.
es gibt ausserdem noch ein paar Aufgaben die für einen korrekten Ablauf notwendig sind.
Dies ist eine Sammelstory dafür.

**Subtasks**
- [x] Kunden registrieren button aus dem Menü entfernen #61
- [x] Applikationslog zur Verfügung stellen #62
- [x] 2 heroku instanzen zum laufen bringen #78
- [x] Buildprozess mit Travis CI umsetzen #63
