### ISSUE TITLE
Buchungen suchen

### ISSUE THREAD

**Issue by chrisitananese** [Tomschi/uni-sese_ws15#64]
Buchungen können auf einer eigenen Seite gesucht werden.
Die Seite zeigt von Anfang an eine Liste aller Buchungen an. Die Liste kann durch Suchkriterien eingeschränkt werden.
Folgende Suchkriterien werden zur Verfügung gestellt:

* Kunde (unterstützt die wildcard ‘*’)
* Zimmer
* Start >= (alle Buchungen mit Startdatum nach oder an “Start”)
* Ende <= (alle Buchungen mit Enddatum vor oder an “Ende”)

Das Ergebnis der Suche wird in einer Tabelle dargestellt. Jede Reihe der Tabelle entspricht einer Buchung und die Spalten enthalten folgende Daten:

* Kundenname
* Zimmer
* Start
* Ende

Zusätzlich wird bei jeder Buchung ein Link angezeigt, der zu einer Detailansicht der Buchung führt.

**Subtasks**
- [x] Alle Suchkriterien getrennt einbauen #71
- [x] Link zur Detailansicht der Buchung einbauen #72
- [x] Detailansicht einer Buchung #73

**Comment by develope80** [comment]
Alle Tasks abgeschlossen
