### ISSUE TITLE
Buchung erstellen (Mitarbeiter)

### ISSUE THREAD

**Issue by chrisitananese** [Tomschi/uni-sese_ws15#9]
Für die Buchung ist die Eingabe folgender Daten notwendig:

* Buchungszeitraum
  * Start
  * Ende
* Anzahl der Personen
*Zimmer
* Kunde

Diese Daten werden durch den Mitarbeiter über die Webseite in folgender Reihenfolge eingegeben:
1. Buchungszeitraum sowie die Anzahl der Personen
2. Zimmer
3. Kunde

Der Kunde kann entweder aus einer Liste aller bestehenden Kunden ausgewählt oder neu eingegeben werden.

Das Zimmer kann aus einer Liste ausgewählt werden, die folgende Kriterien berücksichtigt:

Für den bereits festgelegten Zeitraum belegte Zimmer werden nicht angezeigt.
Es werden nur Zimmer angezeigt, welche die erforderliche Kapazität haben.

Der Rabatt wird aus dem Kundendatensatz entnommen und zur Buchung gespeichert. Der Preis wird automatisch berechnet und zur Buchung gespeichert. Der Preis berechnet sich durch folgende Formel:

_Preis = Zimmerpreis * Anzahl der Nächte * ((100 - Rabatt) / 100)_

Der Zimmerpreis wird aus dem Zimmerdatensatz entnommen. Die Anzahl der Nächte wird aus dem Buchungszeitraum berechnet. Der Rabatt wird wie oben beschrieben aus dem Kundendatensatz übernommen.

Nachdem die Buchung erstellt wurde, wird ein entsprechender Eintrag in ein logfile geschrieben.

**Subtasks**
- [x] Seite zur Auswahl von Datum & Personen #65
- [x] Zimmersuchseite fixen #66
- [x] Seite zur Auswahl eines Kunden erstellen #67
- [x] Abschluß der Buchung #68
- [x]  Datepicker fixen #80 
- [x] RoomService.findAvailable(3) implementieren #81 
- [x] Neu anlegen eines Kunden in CustomerSelectPanel einbauen #82 
- [x] ReservationService.create(3) muss prüfen ob das Zimmer noch verfügbar ist. #83 
- [x] Reservierung erstellen verschönern #84 
- [x] Reservierung erstellen - neuen Kunden anlegen #102

**Comment by alex3772** [comment]
nicht nach spezifikation abgeschlossen.

**Comment by develope80** [comment]
Alle Tasks abgeschlossen
